Fix NPE + add tags
step-up-labs/Droppy pull request #1
Opened 2017-10-03 09:54 UTC by JosefHruska

2017-10-03 11:42 UTC, davidvavra requested changes
Co ta statická metoda? Nechceme ten tag exposovat ven do aplikace

2017-10-03 11:59 UTC, davidvavra requested changes

2017-10-03 11:59 UTC, davidvavra commented on library/src/main/java/com/shehabic/droppy/DroppyMenuManager.java
> +public final class DroppyMenuManager {
Rename to just Droppy

2017-10-03 11:59 UTC, davidvavra commented on library/src/main/java/com/shehabic/droppy/DroppyMenuManager.java
> +    public static void dismissPopup(Activity activity) {
Rename to dismissAllPopups

2017-10-03 11:59 UTC, davidvavra commented on library/src/main/java/com/shehabic/droppy/DroppyMenuManager.java
> +    public static void dismissPopup(Fragment fragment) {
Same

2017-10-04 12:02 UTC, JosefHruska commented
Co nemá být statická metoda? dismiss(Window)? To musí být statické jinak by tu metodu nemohli volat ty dvě statické metody dismissAllPopups(...) a exposnuté to není, ne? Vždyť je to private, tak to od jinud volat nejde.

2017-10-04 12:29 UTC, merged